package port

import (
	"context"
	"io"
)

// ObjectStorage is the driven (secondary) port for storing and retrieving
// arbitrary binary objects (e.g. images) by key. It is implemented by
// outbound adapters: adapter/storage/local and adapter/storage/s3.
//
// PutURL/GetURL are the system's one and only pattern for uploading and
// downloading an object — a presigned-style URL the client uses directly,
// bypassing this backend for the actual bytes, always. Every adapter must
// return a real, usable URL from both; there is no "adapter doesn't
// support this" fallback. adapter/storage/s3 hands back a real S3
// presigned URL; adapter/storage/local, which has no external URL for a
// file on disk, points back at this backend's own /objects/:key routes
// (see registerObjectRoutes) instead — from a caller's point of view, the
// two are indistinguishable.
//
// Put/Get (this backend streaming the bytes itself) still exist because
// something has to actually move the bytes for adapter/storage/local's
// self-serving routes, and because a real implementation needs ordinary
// read/write primitives regardless of the presigned-URL pattern built on
// top of them — but callers outside the object storage adapters
// themselves (e.g. EquipmentModelService) never call these directly.
//
// Keys are always generated by callers (see EquipmentModelService's use of
// this port), never derived from untrusted input, so implementations don't
// need to defend against key-based injection beyond basic sanity checks.
type ObjectStorage interface {
	// Put stores the contents of r under key with the given contentType,
	// overwriting any existing object already stored at that key.
	Put(ctx context.Context, key string, r io.Reader, contentType string) error

	// PutURL returns a URL the client can PUT key's bytes (as
	// contentType) to directly. Only valid for a limited time.
	PutURL(ctx context.Context, key string, contentType string) (url string, err error)

	// Get returns a reader for the object at key, along with the
	// contentType it was stored with. Callers must Close the reader.
	// Returns a *model.Error with model.ErrCodeObjectNotFound if key
	// doesn't exist.
	Get(ctx context.Context, key string) (r io.ReadCloser, contentType string, err error)

	// GetURL returns a URL the client can be redirected to, to fetch
	// key's bytes directly. Only valid for a limited time.
	GetURL(ctx context.Context, key string) (url string, err error)

	// Delete removes the object at key. Deleting a key that doesn't exist
	// is not an error.
	Delete(ctx context.Context, key string) error
}
